name: gruntdotapi
description: A package to deal with halo infinite made by gruntdotapi - Zeny
version: 1.0.0
repository: https://github.com/MaelMbange/gruntdotapi

environment:
  sdk: ^3.4.4

dependencies:
  http: ^1.2.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
